### ISSUE TITLE
Missing File "nih_bluebert_14.npy" when running the code

### ISSUE THREAD

**Issue by MailSuesarn** [cyh-0/BoMD#1]
Hi Yuanhong,

I hope this message finds you well. My name is Suesarn Wilainuch, and we have been in contact via email recently. I reached out to you requesting access to the BoMD code, and I am excited to try out your work.

Firstly, I want to express my gratitude for your prompt response and for granting me access to your repository. It means a lot to me to have the opportunity to explore and learn from your impressive work.

I am reaching out to you today because I encountered a minor issue while running the BoMD code. It seems that there is a missing file named "nih_bluebert_14.npy." This file is required for the execution of the *'load_word_vec'* function, and without it, the code cannot proceed.

**Error Message:**
```
FileNotFoundError: [Errno 2] No such file or directory: './embeddings/bluebert/nih_bluebert_14.npy'
```

**Function with the Issue:**
```python
def load_word_vec(args, norm=True):
    fn = f"{args.train_data.lower()}_{args.bert_name}_{args.num_classes}.npy"
    logger.bind(stage="CONFIG").critical(f"Loading word embedding {fn}")
    wordvec_array = np.load(f"./embeddings/{args.bert_name}/{fn}")

    # ... (rest of the function)
```
**Request:**
1. If it's not too much trouble, could you kindly provide the missing file "nih_bluebert_14.npy"? I assume it should be available within the "./embeddings/{args.bert_name}/" directory. I have searched through the repository but couldn't find it.

2. Additionally, if possible, could you please guide me on how to create the "nih_bluebert_14.npy" file? It would be beneficial for me to understand the steps or data sources needed to generate this file, in case I need to recreate it in the future.

I apologize for any inconvenience this may cause, and I truly appreciate your support and assistance in resolving this issue.

On a personal note, I feel thrilled to finally see your great work publicly available. Your contributions to the field are truly inspiring, and I am looking forward to exploring BoMD further.

Thank you once again for your kind consideration, and I am eagerly waiting to continue my work with BoMD.

Best regards,
Suesarn Wilainuch

**Comment by cyh-0** [comment]
[embeddings.tar.gz](https://github.com/cyh-0/BoMD/files/12236145/embeddings.tar.gz)

**Comment by cyh-0** [comment]
Hi Suesarn,

I have attached the tar file for the embeddings and generator's code. See if you can download the file.

Cheers,
Yuanhong

**Comment by MailSuesarn** [comment]
> Hi Suesarn,
> 
> I have attached the tar file for the embeddings and generator's code. See if you can download the file.
> 
> Cheers, Yuanhong

Thank you so much for your prompt response and for providing the "nih_bluebert_14.npy" file. I really appreciate your help with resolving the issue.

I have successfully downloaded the tar file containing the embeddings, and I'm looking forward to exploring the BoMD code further with the file in place.

As I was running the code, I encountered a FileNotFoundError related to the model weight file *"1e25dlaj_model_cls_19.pth."* 

I would like to inquire about the importance of this particular model weight. Is it essential for the functionality of the code, or can I skip loading this weight? Could you please provide some insights into the significance of using *"1e25dlaj_model_cls_19.pth"* versus the *"Baseline-MLSM.pth"* weight, especially in the context of the NIH dataset?

Here's the part of the code where the model weight is loaded:

```python
if args.train_data == "NIH":
    if args.trim_data:
        self.backbone.load_state_dict(
            torch.load("./ckpt/1e25dlaj_model_cls_19.pth")["net"]
        )
    else:
        self.backbone.load_state_dict(
            torch.load("./ckpt/Baseline-MLSM.pth")["net"]
        )

**Comment by MailSuesarn** [comment]
> Hi Suesarn,
> 
> I have attached the tar file for the embeddings and generator's code. See if you can download the file.
> 
> Cheers, Yuanhong

However, while reviewing the provided files, I couldn't find the generator's code that is responsible for generating the *"nih_bluebert_14.npy"* file. This file is of particular interest to me, as I am eager to understand the process behind its creation and its significance in the project.

If it's not too much trouble, could you please share the generator's code with me or provide any additional information on how I can access it? Having insights into the generator's implementation would greatly enhance my understanding of the project and the role of "nih_bluebert_14.npy" in it.

**Comment by cyh-0** [comment]
> > Hi Suesarn,
> > I have attached the tar file for the embeddings and generator's code. See if you can download the file.
> > Cheers, Yuanhong
> 
> However, while reviewing the provided files, I couldn't find the generator's code that is responsible for generating the _"nih_bluebert_14.npy"_ file. This file is of particular interest to me, as I am eager to understand the process behind its creation and its significance in the project.
> 
> If it's not too much trouble, could you please share the generator's code with me or provide any additional information on how I can access it? Having insights into the generator's implementation would greatly enhance my understanding of the project and the role of "nih_bluebert_14.npy" in it.

The generation file is the biobert.py file inside embeddings.tar.gz

**Comment by cyh-0** [comment]
> > Hi Suesarn,
> > I have attached the tar file for the embeddings and generator's code. See if you can download the file.
> > Cheers, Yuanhong
> 
> Thank you so much for your prompt response and for providing the "nih_bluebert_14.npy" file. I really appreciate your help with resolving the issue.
> 
> I have successfully downloaded the tar file containing the embeddings, and I'm looking forward to exploring the BoMD code further with the file in place.
> 
> As I was running the code, I encountered a FileNotFoundError related to the model weight file _"1e25dlaj_model_cls_19.pth."_
> 
> I would like to inquire about the importance of this particular model weight. Is it essential for the functionality of the code, or can I skip loading this weight? Could you please provide some insights into the significance of using _"1e25dlaj_model_cls_19.pth"_ versus the _"Baseline-MLSM.pth"_ weight, especially in the context of the NIH dataset?
> 
> Here's the part of the code where the model weight is loaded:
> 
> ```python
> if args.train_data == "NIH":
>     if args.trim_data:
>         self.backbone.load_state_dict(
>             torch.load("./ckpt/1e25dlaj_model_cls_19.pth")["net"]
>         )
>     else:
>         self.backbone.load_state_dict(
>             torch.load("./ckpt/Baseline-MLSM.pth")["net"]
>         )
> ```

here is the warmup ckpt

**Comment by cyh-0** [comment]
> > Hi Suesarn,
> > I have attached the tar file for the embeddings and generator's code. See if you can download the file.
> > Cheers, Yuanhong
> 
> Thank you so much for your prompt response and for providing the "nih_bluebert_14.npy" file. I really appreciate your help with resolving the issue.
> 
> I have successfully downloaded the tar file containing the embeddings, and I'm looking forward to exploring the BoMD code further with the file in place.
> 
> As I was running the code, I encountered a FileNotFoundError related to the model weight file _"1e25dlaj_model_cls_19.pth."_
> 
> I would like to inquire about the importance of this particular model weight. Is it essential for the functionality of the code, or can I skip loading this weight? Could you please provide some insights into the significance of using _"1e25dlaj_model_cls_19.pth"_ versus the _"Baseline-MLSM.pth"_ weight, especially in the context of the NIH dataset?
> 
> Here's the part of the code where the model weight is loaded:
> 
> ```python
> if args.train_data == "NIH":
>     if args.trim_data:
>         self.backbone.load_state_dict(
>             torch.load("./ckpt/1e25dlaj_model_cls_19.pth")["net"]
>         )
>     else:
>         self.backbone.load_state_dict(
>             torch.load("./ckpt/Baseline-MLSM.pth")["net"]
>         )
> ```

you can download the first one here "https://drive.google.com/file/d/1XFey_pxTC8Udl738T-P0ttMyucflfI_r/view?usp=sharing". The second one is deprecated a long time ago.

**Comment by MailSuesarn** [comment]
> > > Hi Suesarn,
> > > I have attached the tar file for the embeddings and generator's code. See if you can download the file.
> > > Cheers, Yuanhong
> > 
> > 
> > Thank you so much for your prompt response and for providing the "nih_bluebert_14.npy" file. I really appreciate your help with resolving the issue.
> > I have successfully downloaded the tar file containing the embeddings, and I'm looking forward to exploring the BoMD code further with the file in place.
> > As I was running the code, I encountered a FileNotFoundError related to the model weight file _"1e25dlaj_model_cls_19.pth."_
> > I would like to inquire about the importance of this particular model weight. Is it essential for the functionality of the code, or can I skip loading this weight? Could you please provide some insights into the significance of using _"1e25dlaj_model_cls_19.pth"_ versus the _"Baseline-MLSM.pth"_ weight, especially in the context of the NIH dataset?
> > Here's the part of the code where the model weight is loaded:
> > ```python
> > if args.train_data == "NIH":
> >     if args.trim_data:
> >         self.backbone.load_state_dict(
> >             torch.load("./ckpt/1e25dlaj_model_cls_19.pth")["net"]
> >         )
> >     else:
> >         self.backbone.load_state_dict(
> >             torch.load("./ckpt/Baseline-MLSM.pth")["net"]
> >         )
> > ```
> 
> you can download the first one here "https://drive.google.com/file/d/1XFey_pxTC8Udl738T-P0ttMyucflfI_r/view?usp=sharing". The second one is deprecated a long time ago.

Thank you so much for providing the *"nih_bluebert_14.npy"* file and the accompanying code. Everything is running perfectly now, and I am excited to explore and learn from your work!

As I continue with my experiments, I now have the confidence to dive deeper into the project, thanks to your guidance. If, at any point, I encounter any challenges or have further questions, I will not hesitate to reach out for your help again.

Once again, thank you for your invaluable support, and I hope to stay connected in the future.
