### ISSUE TITLE
Could BoMD perform inference on all 14 diseases of CheXpert?

### ISSUE THREAD

**Issue by Kingofolk** [cyh-0/BoMD#3]
Hi! Thanks for your great work. I was wondering whether your work could perform inference on all 14 diseases of CheXpert? If yes, could you please share your finall checkpoint and give me some instructions about how to utilize it to inference all 14 diseases of CheXpert?
Best regards
Kingofolk

**Comment by cyh-0** [comment]
Sorry @Kingofolk , for ChestXpert I only preserve 8 diseases, which are the intersections between ChestXpert and OpenI/PadChest. I haven't performed evaluations on the original CheXpert splits.

Cheers,
Yuanhong

**Comment by Kingofolk** [comment]
Thanks for your reply. Hope you have a nice day.
