### ISSUE TITLE
word embedding

### ISSUE THREAD

**Issue by axz520** [cyh-0/BoMD#7]
when run load_word_vec，the code cannot find f"{args.train_data.lower()}_{args.bert_name}_{args.num_classes}.npy" any npy file.Counld you share the bert word embedding for chest X-ray？

**Comment by axz520** [comment]
> when run load_word_vec，the code cannot find f"{args.train_data.lower()}_{args.bert_name}_{args.num_classes}.npy" any npy file.Counld you share the bert word embedding for chest X-ray？

经过处理的OpenI & PadChest也可以从 https://drive.google.com/drive/folders/1tSNMHxhs98AFctTOur9MTMLhYfiKEJ_- 这里下载
Thanks！

**Comment by cyh-0** [comment]
You can download the embeddings from the following URL "https://drive.google.com/drive/folders/1S3kL6KGtom_LTsqivdrlbdz_yXYKH8aE?usp=sharing"
